services:
  server:
    build: .
    ports:
      - "8083:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpwd

